/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "wator.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_cell_to_char();
extern void test_char_to_cell();
extern void test_new_planet();
extern void test_print_planet();
extern void test_load_planet();
extern void test_shark_rule1();
extern void test_shark_rule2();
extern void test_fish_rule3();
extern void test_fish_rule4();
extern void test_move_cell();


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("test_wator.c");
  RUN_TEST(test_cell_to_char, 14);
  RUN_TEST(test_char_to_cell, 22);
  RUN_TEST(test_new_planet, 30);
  RUN_TEST(test_print_planet, 38);
  RUN_TEST(test_load_planet, 59);
  RUN_TEST(test_shark_rule1, 66);
  RUN_TEST(test_shark_rule2, 86);
  RUN_TEST(test_fish_rule3, 104);
  RUN_TEST(test_fish_rule4, 121);
  RUN_TEST(test_move_cell, 137);

  return (UnityEnd());
}
